# NAME: Jiaping Zeng
# EMAIL: jiapingzeng@ucla.edu
# ID: 905363270

dist_files = *.png *.jpg Makefile README

default: dist

dist: lab4a-905363270.tar.gz

lab4a-905363270.tar.gz:
	tar -czf $@ $(dist_files)